# -*- coding: utf-8 -*-
# !/usr/bin/env python

errorProcessSector=u'Error when processing sector.'
p1label=u'empty easy no cover'
p2label=u'empty easy with cover'
p3label=u'empty difficult'
p4label=u'cover easy to pass'
p5label=u'cover difficult to pass'
p6label=u'intravilan'
p7label=u'parks and playgrounds with people'
p8label=u'parks and playgrounds without people'
p9label=u'water body'
p10label=u'other'
typesOfLanduse=u'Types of terrain'
handlersLabel=u'Handlers'
areaForhandlersLabel=u'Area suitable for handler is'
availableLabel=u'There are available'
handlersLabel2=u'handlers'
searchingForTime=u'They search area in about'
handlersSubstitute=u'The area contains parts where the handlers may be substituted by searchers in a formation. The area is'
dronArea=u'The area contains parts that are suitable for helicopter (drone) of'
searchersLabel=u'Searchers in formation'
searchersArea=u'The area suitable for searchers in formation is'
searchersLabel2=u'persons for search formation'
noSearchers=u'There are not any searchers for formation. You have to call some'
diverLabel=u'Diver'
waterArea=u'Water bodies have'
diverLabel=u'divers'
noDivers=u'There are not any divers. You have to call some'
timeLabel=u'Search in specified time'
searchUntil=u'To search in'
unitsNeeded=u'hours you need'
atLeastOneDiver=u'At least one diver'
atLeastOneDrone=u'At least one helicopter (drone)'
