# -*- coding: utf-8 -*-
# !/usr/bin/env python

errorProcessSector=u'Помилка під час обробки сектора.'
p1label=u'порожній легкий без покриття'
p2label=u'порожній легко з кришкою'
p3label=u'порожній важко'
p4label=u'обкладинку легко пройти'
p5label=u'покриття важко пройти'
p6label=u'внутрішньосельський'
p7label=u'парки та дитячі майданчики з людьми'
p8label=u'парки та дитячі майданчики без людей'
p9label=u'водойма'
p10label=u'інше'
typesOfLanduse=u'Типи рельєфу'
handlersLabel=u'Обробники'
areaForhandlersLabel=u'Область, придатна для обробки, це'
availableLabel=u'Є в наявності'
handlersLabel2=u'кінологи'
searchingForTime=u'Вони шукають область приблизно в'
handlersSubstitute=u'Область містить частини, де обробники можуть бути замінені шукачами у формуванні. Район є'
dronArea=u'Ця зона містить частини, які підходять для вертольота (дрона)'
searchersLabel=u'Шукачі в формуванні'
searchersArea=u'Область, придатна для шукачів у формуванні, це'
searchersLabel2=u'персони для формування пошуку'
noSearchers=u'Немає шукачів формування. Ви повинні подзвонити декому'
diverLabel=u'Водолаз'
waterArea=u'Водойми мають'
diverLabel=u'Водолази'
noDivers=u'Немає дайверів. Ви повинні подзвонити декому'
timeLabel=u'Пошук у вказаний час'
searchUntil=u'Шукати в'
unitsNeeded=u'години, які вам потрібні'
atLeastOneDiver=u'Принаймні один дайвер'
atLeastOneDrone=u'Принаймні один вертоліт (дрон)'
