# -*- coding: utf-8 -*-
# !/usr/bin/env python

errorProcessSector=u'Při zpracování sektoru nastala chyba.'
p1label=u'volný schůdný bez porostu'
p2label=u'volný schůdný s porostem'
p3label=u'volný obtížně schůdný'
p4label=u'porost lehce průchozí'
p5label=u'porost obtížně průchozí'
p6label=u'zastavěné území měst a obcí'
p7label=u'městské parky a hřiště s pohybem osob'
p8label=u'městské parky a hřiště bez osob'
p9label=u'vodní plocha'
p10label=u'ostatní plochy'
typesOfLanduse=u'Typy povrchů'
handlersLabel=u'Psovodi'
areaForhandlersLabel=u'Plocha pro pátrání vhodná pro psovoda je'
availableLabel=u'K dispozici je'
handlersLabel2=u'psovodů'
searchingForTime=u'Oblast propátrají přibližně za'
handlersSubstitute=u'Součástí je prostor, kde je možno psovody nahradit rojnicí. Jedná se o'
dronArea=u'Součástí je prostor vhodný pro vrtulník (dron) o rozloze'
searchersLabel=u'Rojnice'
searchersArea=u'Plocha pro pátrání vhodná pro rojnici je'
searchersLabel2=u'osob pro rojnici'
noSearchers=u'Nejsou k dispozici žádní pátrači do rojnice. Je nutné nějaké zajistit'
diverLabel=u'Potápěč'
waterArea=u'Vodní plochy v oblasti mají'
diverLabel2=u'potápěčů'
noDivers=u'Nejsou k dispozici žádní potápěči. Je nutné nějaké zajistit'
timeLabel=u'Propátrání do stanoveného času'
searchUntil=u'K propátrání do'
unitsNeeded=u'hodin potřebujete'
atLeastOneDiver=u'Minimálně jeden potápěč'
atLeastOneDrone=u'Minimálně jeden vrtulník (dron)'